micronaut:
  application:
    name: carrosGrpc
datasources:
  default:
    url: jdbc:mysql://localhost:3306/carros_grpc?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    schema-generate: CREATE_DROP
    dialect: MySQL8Dialect
jpa.default.properties.hibernate.hbm2ddl.auto: update
